version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"
    volumes:
      - /home/matheus/Documents/projects/dbs/pg-poc:/var/lib/postgresql/data